apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-fargate
  region: us-east-1

vpc:
    subnets:
        private:
            us-east-1a:
                id: "subnet-01c929f1exxxxx"
            us-east-1b:
                id: "subnet-07cff415fxxxx"
        public:
            us-east-1a:
                id: "subnet-0c80dd3cxxxxx"
            us-east-1b:
                id: "subnet-0e722c9fxxxx"

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
